/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
static yyconst short int yy_acclist[280] =
    {   0,
       72,   70,   71,   20,   70,   71,   38,   71,   70,   71,
       70,   71,   66,   70,   71,   69,   70,   71,   58,   70,
       71,   59,   70,   71,   64,   70,   71,   63,   70,   71,
       56,   70,   71,   62,   70,   71,   65,   70,   71,   22,
       70,   71,   22,   70,   71,   53,   70,   71,   67,   70,
       71,   57,   70,   71,   68,   70,   71,   19,   70,   71,
       60,   70,   71,   61,   70,   71,   19,   70,   71,   19,
       70,   71,   19,   70,   71,   19,   70,   71,   19,   70,
       71,   19,   70,   71,   19,   70,   71,   19,   70,   71,
       19,   70,   71,   19,   70,   71,   19,   70,   71,   54,

       70,   71,   70,   71,   55,   70,   71,   70,   71,   24,
       71,   24,   71,   25,   71,   24,   71,   24,   71,   33,
       71,   30,   33,   71,   32,   71,   33,   71,   33,   71,
       20,   52,   36,   35,   45,   47,   43,   40,   22,   22,
       41,   39,   42,   46,   23,   34,   44,   22,   37,   22,
       37,   37,   49,   51,   50,   19,   19,   19,   19,   11,
       19,   19,   19,   19,    7,   19,   19,   19,   19,   19,
       19,   19,   19,   48,   24,   26,   27,   30,   22,   34,
       21,   21,   37,   19,   19,   19,   19,   19,   19,   19,
        4,   19,    1,   19,   19,   19,   19,   19,   19,   19,

       31,   29,   21,   21,   37,   19,   19,   15,   19,   19,
       19,   19,    8,   19,   19,    2,   19,   19,   19,   19,
       12,   19,   19,   19,    5,   19,   16,   19,   19,   19,
       19,   17,   19,   19,    3,   19,   19,   10,   19,   19,
       19,   18,   19,   13,   19,    9,   19,   14,   19,   19,
       19,   19,    6,   19,   28,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19
    } ;

static yyconst short int yy_accept[196] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
        9,   11,   13,   16,   19,   22,   25,   28,   31,   34,
       37,   40,   43,   46,   49,   52,   55,   58,   61,   64,
       67,   70,   73,   76,   79,   82,   85,   88,   91,   94,
       97,  100,  103,  105,  108,  110,  112,  114,  116,  118,
      120,  122,  125,  127,  129,  131,  132,  133,  133,  134,
      135,  136,  137,  138,  139,  140,  141,  142,  143,  144,
      145,  146,  147,  148,  149,  150,  152,  153,  153,  154,
      155,  156,  157,  158,  159,  160,  162,  163,  164,  165,
      167,  168,  169,  170,  171,  172,  173,  174,  175,  175,

      176,  177,  178,  179,  179,  179,  180,  181,  182,  184,
      185,  186,  187,  188,  189,  190,  191,  193,  195,  196,
      197,  198,  199,  200,  201,  201,  202,  203,  204,  206,
      207,  208,  210,  211,  212,  213,  215,  216,  218,  219,
      220,  221,  223,  224,  224,  225,  227,  229,  230,  231,
      232,  234,  235,  237,  238,  240,  240,  241,  242,  244,
      246,  248,  250,  250,  251,  252,  252,  253,  255,  256,
      257,  258,  259,  260,  261,  262,  263,  264,  265,  266,
      267,  268,  269,  270,  271,  272,  273,  274,  275,  276,
      277,  278,  279,  280,  280

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,    1,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,   19,
       20,   21,    1,    1,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   23,   22,   22,   22,   22,
       22,   22,   22,   22,   23,   22,   22,   24,   22,   22,
       25,    1,   26,    1,   27,    1,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   22,   37,   38,   22,   39,
       40,   22,   22,   41,   42,   43,   44,   45,   46,   24,
       22,   22,   47,   48,   49,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[50] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    4,    1,    5,    1,
        5,    6,    6,    6,    1,    1,    6,    4,    4,    4,
        4,    4,    4,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    7,    1
    } ;

static yyconst short int yy_base[234] =
    {   0,
        0,  302,   48,   50,   52,   64,  305,  325,  300,  325,
      279,   53,  276,  285,  325,  325,  270,   56,  325,   61,
       59,   68,   70,  325,  267,  264,  261,    0,  325,  325,
      237,   60,  235,  234,   22,   56,  229,  234,   55,  223,
      225,  325,  209,  325,  218,  325,  249,  325,  233,  234,
      325,  240,  325,    0,    0,  237,  325,   91,  325,  325,
      325,  325,  325,  325,   81,   86,  325,  325,  325,  325,
      325,    0,  325,    0,   94,  104,  137,    0,  325,  325,
      325,    0,  204,  187,  186,  178,  174,  175,  171,    0,
      165,  145,  140,  142,  145,  144,  143,  325,  139,  175,

      325,  325,  174,  170,  153,  325,    0,   84,   94,    0,
      145,  140,   84,  135,  131,  134,    0,    0,  127,  116,
      118,  115,  126,  118,  125,  325,  325,  325,  123,    0,
      114,    0,  107,  113,  110,  111,  103,    0,  104,  101,
      113,    0,  109,   99,    0,    0,    0,   97,  103,  101,
        0,   94,    0,   96,    0,   79,    0,   71,    0,    0,
        0,    0,   82,    0,   67,   48,    0,    0,  325,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  325,  325,  185,  192,  199,  203,  207,  213,

      220,  227,   60,  231,  234,  237,  240,  243,  246,  249,
      252,  255,  258,  261,  264,  267,  270,  273,  276,  279,
      282,  285,  288,  291,  294,  297,  300,  303,  306,  309,
      312,  315,  318
    } ;

static yyconst short int yy_def[234] =
    {   0,
      194,    1,  195,  195,  196,  196,  194,  194,  194,  194,
      194,  197,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  198,  198,  194,  194,  194,  194,  199,  194,  194,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  200,  201,  194,  194,  197,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  202,  194,   23,  198,  198,  198,  203,  194,  194,
      194,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  194,  194,  194,

      194,  194,  194,  200,  201,  194,  202,  203,   77,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  194,  194,  194,  194,  198,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  194,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  194,  208,  208,  208,  208,
      208,  208,  194,  209,  209,  194,  210,  210,  194,  211,
      212,  213,  214,  215,  216,  217,  218,  219,  220,  221,
      222,  223,  224,  225,  226,  227,  228,  229,  230,  231,
      232,  233,  194,    0,  194,  194,  194,  194,  194,  194,

      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194
    } ;

static yyconst short int yy_nxt[375] =
    {   0,
        8,    9,   10,   11,   12,    8,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   28,   28,   29,   30,   28,   28,   31,   32,
       33,   34,   35,   28,   28,   36,   28,   37,   28,   28,
       38,   39,   28,   28,   40,   41,   42,   43,   44,   47,
       48,   47,   48,   52,   53,   59,   54,   60,   49,   88,
       49,   89,   50,  108,   50,   52,   53,   64,   54,   71,
       55,   65,   66,   72,   68,   67,   65,   66,   73,  169,
       69,   70,   55,   74,   74,   74,   74,   84,   90,   94,
       76,   77,   76,   59,   91,   60,   66,   66,  168,   85,

       95,   66,   66,  106,   78,   76,  128,   76,  106,  194,
      194,   76,  166,   76,  165,   78,  129,  194,  106,  194,
      194,  128,  163,  106,  106,  133,  134,  128,   78,  106,
      162,  129,  161,  160,  159,  158,  156,  129,  194,  194,
      155,  194,  154,  153,  152,  151,  150,  149,  148,  147,
      146,  194,  108,  108,  144,  143,  142,  141,  140,  139,
      138,  137,  136,  135,  109,  109,  109,  109,  109,  109,
      194,  132,  131,  127,  126,  103,  100,  125,  124,  123,
      122,  121,  120,  119,  194,   46,   46,   46,   46,   46,
       46,   46,   51,   51,   51,   51,   51,   51,   51,   58,

       58,   58,   58,   58,   58,   58,   75,  118,   75,   75,
       82,  117,   82,  104,  116,  115,  104,  104,  104,  104,
      105,  114,  105,  105,  113,  105,  105,  107,  112,  107,
      107,  107,  107,  107,  110,  111,  110,  130,   56,  130,
      145,  103,  145,  157,  102,  157,  164,  101,  164,  167,
      100,  167,  170,   99,  170,  171,   98,  171,  172,   97,
      172,  173,   96,  173,  174,   93,  174,  175,   92,  175,
      176,   87,  176,  177,   86,  177,  178,   83,  178,  179,
       81,  179,  180,   80,  180,  181,   79,  181,  182,   63,
      182,  183,   62,  183,  184,   61,  184,  185,   57,  185,

      186,   56,  186,  187,  194,  187,  188,   45,  188,  189,
      194,  189,  190,  194,  190,  191,  194,  191,  192,  194,
      192,  193,  194,  193,    7,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194
    } ;

static yyconst short int yy_chk[375] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    4,    4,    5,    5,   12,    5,   12,    3,   35,
        4,   35,    3,  203,    4,    6,    6,   18,    6,   21,
        5,   18,   18,   21,   20,   18,   20,   20,   21,  166,
       20,   20,    6,   22,   22,   23,   23,   32,   36,   39,
       22,   22,   23,   58,   36,   58,   65,   65,  165,   32,

       39,   66,   66,   65,   65,   22,  108,   23,   66,   75,
       75,   22,  163,   23,  158,   22,  109,   23,   65,   76,
       76,  108,  156,   66,   65,  113,  113,  108,   65,   66,
      154,  109,  152,  150,  149,  148,  144,  109,  129,  129,
      143,   75,  141,  140,  139,  137,  136,  135,  134,  133,
      131,   76,   77,   77,  125,  124,  123,  122,  121,  120,
      119,  116,  115,  114,   77,   77,   77,   77,   77,   77,
      129,  112,  111,  105,  104,  103,  100,   99,   97,   96,
       95,   94,   93,   92,   77,  195,  195,  195,  195,  195,
      195,  195,  196,  196,  196,  196,  196,  196,  196,  197,

      197,  197,  197,  197,  197,  197,  198,   91,  198,  198,
      199,   89,  199,  200,   88,   87,  200,  200,  200,  200,
      201,   86,  201,  201,   85,  201,  201,  202,   84,  202,
      202,  202,  202,  202,  204,   83,  204,  205,   56,  205,
      206,   52,  206,  207,   50,  207,  208,   49,  208,  209,
       47,  209,  210,   45,  210,  211,   43,  211,  212,   41,
      212,  213,   40,  213,  214,   38,  214,  215,   37,  215,
      216,   34,  216,  217,   33,  217,  218,   31,  218,  219,
       27,  219,  220,   26,  220,  221,   25,  221,  222,   17,
      222,  223,   14,  223,  224,   13,  224,  225,   11,  225,

      226,    9,  226,  227,    7,  227,  228,    2,  228,  229,
        0,  229,  230,    0,  230,  231,    0,  231,  232,    0,
      232,  233,    0,  233,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "clex.l"
#define INITIAL 0
#line 2 "clex.l"

#include <stdlib.h>
#include <stdio.h>
#include "symboltable.h"
#include "tokens.h"

entry_t** symbol_table;
entry_t** constant_table;
int cmnt_strt = 0;

/* Exclusive states */
#define CMNT 1

#define PREPROC 2

#line 578 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 25 "clex.l"

  /* Keywords*/
#line 735 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yy_c_buf_p - yytext_ptr;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 195 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 325 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 27 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 32 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 33 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 34 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 35 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 36 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 37 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 38 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 39 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 40 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 41 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 42 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 43 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 44 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Keyword");}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "clex.l"
{printf("\t%-30s : %s\n", yytext,"IDENTIFIER");
                                  insert( symbol_table,yytext,IDENTIFIER );}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "clex.l"
;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "clex.l"
{printf("\t%-30s : %s\n", yytext,"Constants");
									insert( constant_table,yytext,HEX_CONSTANT);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 51 "clex.l"
{printf("\t%-30s : %s\n", yytext,"Constants");
									insert( constant_table,yytext,DEC_CONSTANT);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 53 "clex.l"
{cmnt_strt = yylineno; BEGIN CMNT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 54 "clex.l"
;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 55 "clex.l"
{yylineno++;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 56 "clex.l"
{BEGIN INITIAL;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 57 "clex.l"
{printf("Line %3d: Nested comments are not valid!\n",yylineno);}
	YY_BREAK
case YY_STATE_EOF(CMNT):
#line 58 "clex.l"
{printf("Line %3d: Unterminated comment\n", cmnt_strt); yyterminate();}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "clex.l"
{BEGIN PREPROC;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "clex.l"
{printf("\t%-30s : %s\n",yytext,"HEADER_FILE");}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 61 "clex.l"
;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 62 "clex.l"
{printf("\t%-30s : %s\n",yytext,"HEADER_FILE");}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 63 "clex.l"
{yylineno++; BEGIN INITIAL;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 64 "clex.l"
{printf("Line %3d: Illegal header file format \n",yylineno);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 65 "clex.l"
;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 67 "clex.l"
{

  if(yytext[yyleng-2]=='\\') /* check if it was an escaped quote */
  {
    yyless(yyleng-1);       /* push the quote back if it was escaped */
    yymore();
  }
  else
  insert( constant_table,yytext,STRING);
 }
	YY_BREAK
case 36:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 78 "clex.l"
{printf("Line %3d: Unterminated string %s\n",yylineno,yytext);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "clex.l"
{printf("Line %3d: Illegal identifier name %s\n",yylineno,yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "clex.l"
{yylineno++;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 91 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 92 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 93 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Punctuation");}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Punctuation");}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Punctuation");}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Punctuation");}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Punctuation");}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Punctuation");}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 102 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Punctuation");}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 103 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Punctuation");}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 104 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 105 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 106 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 107 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 108 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 109 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 110 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Operator");}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 111 "clex.l"
{printf("\t%-30s : %s\n",yytext,"Special Symbol");}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 112 "clex.l"
{printf("Line %3d: Illegal character %s\n",yylineno,yytext);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 114 "clex.l"
ECHO;
	YY_BREAK
#line 1207 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(PREPROC):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 195 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 195 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 194);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 114 "clex.l"

int yywrap() {
    // Add your yywrap logic here
    return 1; // Indicate end of input
}
int main()
{
  yyin=fopen("a.c","r");
  symbol_table=create_table();
  constant_table=create_table();
  yylex();
  printf("\n\tSymbol table");
  display(symbol_table);
  printf("\n\tConstants Table");
  display(constant_table);
  printf("NOTE: Please refer tokens.h for token meanings\n");
}